# Generated by Django 4.2 on 2023-06-02 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(help_text='Цель', max_length=20, verbose_name='Цель')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Podgoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podgoal', models.CharField(max_length=20, verbose_name='подцель')),
                ('checked', models.CharField(default='false', max_length=5, verbose_name='Сделано')),
                ('index', models.CharField(default='4', max_length=5, verbose_name='Индекс')),
                ('goal', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='goals.goals', verbose_name='цель')),
            ],
            options={
                'ordering': ['goal'],
            },
        ),
    ]
