# Generated by Django 4.2 on 2023-05-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podgoals',
            name='index',
            field=models.CharField(default='4', max_length=5, verbose_name='Индекс'),
        ),
    ]
