# Generated by Django 4.2 on 2023-05-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Podgoals',
            new_name='Podgoal',
        ),
        migrations.AlterField(
            model_name='goals',
            name='goal',
            field=models.CharField(help_text='Цель', max_length=20, verbose_name='Цель'),
        ),
    ]
