# Generated by Django 4.2 on 2023-06-02 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='podgoals',
            name='user',
            field=models.ForeignKey(default='4', max_length=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID_user'),
        ),
        migrations.AddField(
            model_name='goals',
            name='user',
            field=models.ForeignKey(default='12', max_length=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID_user'),
        ),
    ]
