# Generated by Django 4.2 on 2023-05-29 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_rename_podgoals_podgoal_alter_goals_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podgoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podgoal', models.CharField(max_length=20, verbose_name='подцель')),
                ('goal', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='goals.goals', verbose_name='цель')),
            ],
            options={
                'ordering': ['goal'],
            },
        ),
        migrations.DeleteModel(
            name='Podgoal',
        ),
    ]
