# Generated by Django 4.2 on 2023-05-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_podgoals_delete_podgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='podgoals',
            name='checked',
            field=models.CharField(default='false', max_length=5, verbose_name='Сделано'),
        ),
    ]
