# Generated by Django 4.2 on 2023-04-26 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delo', models.CharField(help_text='Введите дело', max_length=40, verbose_name='Дело')),
                ('importance', models.CharField(choices=[('I', 'Важно'), ('M', 'Средне'), ('N', 'Не важно')], default='I', max_length=8)),
                ('user_id', models.ForeignKey(help_text='Введите id', on_delete=django.db.models.deletion.CASCADE, to='registration.user', verbose_name='ID')),
            ],
            options={
                'ordering': ['user_id', 'importance'],
            },
        ),
    ]
