# Generated by Django 4.2 on 2023-06-02 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(help_text='Введите дело', max_length=40, verbose_name='Дело')),
                ('checked', models.CharField(default='false', max_length=5, verbose_name='Сделано')),
                ('important', models.CharField(max_length=5, verbose_name='Важность')),
                ('day', models.CharField(max_length=5, verbose_name='День')),
                ('month', models.CharField(max_length=5, verbose_name='Месяц')),
                ('year', models.CharField(max_length=5, verbose_name='Год')),
                ('user', models.ForeignKey(default='12', max_length=10, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID_user')),
            ],
            options={
                'ordering': ['user', 'year', 'month', 'day', '-important'],
            },
        ),
    ]
