# Generated by Django 4.2 on 2023-05-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['user_id', 'year', 'month', 'day', '-important']},
        ),
        migrations.AddField(
            model_name='todolist',
            name='user_id',
            field=models.CharField(default='12', max_length=10, verbose_name='ID'),
        ),
    ]
