# Generated by Django 4.2 on 2023-05-07 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0002_alter_todolist_options_todolist_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['id', 'year', 'month', 'day', '-important']},
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='id',
            field=models.ForeignKey(default='12', max_length=10, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='ID_user'),
        ),
    ]
