# Generated by Django 4.2 on 2023-05-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_todolist_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='checked',
            field=models.CharField(default='false', max_length=5, verbose_name='Сделано'),
        ),
    ]
